@StockTW.Server_HostAddress = http://localhost:5183


GET {{StockTW.Server_HostAddress}}/stock/
Accept: application/json

GET {{StockTW.Server_HostAddress}}/users/
Accept: application/json

POST {{StockTW.Server_HostAddress}}/users/login/
Accept: application/json